// All user-facing text, in French (FR-030).
export const STRINGS = {
  appTitle: 'Rush Hour',
  roadmapTitle: 'Choisissez votre défi',
  roadmapHint: 'Avancez sur la route : résolvez un défi pour débloquer le suivant.',
  locked: 'Défi verrouillé',
  lockedHint: 'Terminez les défis précédents pour débloquer celui-ci.',
  solved: 'Réussi',
  best: 'Meilleur',
  moves: 'déplacements',
  movesShort: 'cps',
  play: 'Jouer',
  replay: 'Rejouer',
  backToRoadmap: 'Retour à la route',
  undo: 'Annuler',
  redo: 'Rétablir',
  reset: 'Recommencer',
  reveal: 'Voir la solution',
  soundOn: 'Couper le son',
  soundOff: 'Activer le son',
  moveCount: 'Déplacements',
  time: 'Temps',
  objective: 'Objectif : sortir la voiture rouge par la sortie à droite.',
  victoryTitle: 'Bravo !',
  victoryOptimal: 'Solution optimale',
  victoryYourScore: 'Votre score',
  victoryRevealed: 'Solution révélée — ce résultat ne compte pas.',
  victoryFinal: 'Vous avez terminé tous les défis !',
  revealPlayback: 'Solution en cours…',
  loading: 'Chargement des défis…',
  loadError: 'Impossible de charger les défis.',
  retry: 'Réessayer',
  level: 'Niveau',
  movesLabel: (n) => `${n} ${n === 1 ? 'déplacement' : 'déplacements'}`,
  roadmapNext: 'Niveau suivant',
  roadmapPrev: 'Niveau précédent',
  roadmapHintDesktop: '▲ / ▼ : se déplacer · Entrée : jouer',
  roadmapHintTouch: '▲ / ▼ ou touchez le cercle voulu',
  blockedEnd: 'Fin de la route',
};
